apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  releaseName: grafana
  targetNamespace: observability
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "10.5.15"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system