apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  releaseName: prometheus
  targetNamespace: observability
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "83.5.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  releaseName: grafana
  targetNamespace: observability
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "10.5.15"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  releaseName: loki
  targetNamespace: observability
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "6.55.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  releaseName: promtail
  targetNamespace: observability
  interval: 5m
  chart:
    spec:
      chart: promtail
      version: "6.17.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  releaseName: tempo
  targetNamespace: observability
  interval: 5m
  chart:
    spec:
      chart: tempo
      version: "1.24.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
