apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  releaseName: prometheus
  targetNamespace: observability
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "83.5.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
  kubeControllerManager:
    enabled: false
    service:
      enabled: false

  kubeScheduler:
    enabled: false
    service:
      enabled: false

  kubeProxy:
    enabled: false

  kubeEtcd:
    enabled: false
    service:
      enabled: false