apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  releaseName: tempo
  targetNamespace: observability
  interval: 5m
  chart:
    spec:
      chart: tempo
      version: "1.24.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system